setup:
  data:
    type: "local"
    source: "__INPUT_DIR__"   # directory containing *.jsonl (or a tmp dir with a symlink)
  mode: "finetuning"
  output_dir: "/home/ebereuwadoka/project3-sparse-ft/data/cs_hdf5/mixtral/boolq/train"
  processes: 8

processing:
  huggingface_tokenizer: "mistralai/Mixtral-8x7B-v0.1"
  max_seq_length: 2048
  read_hook: "cerebras.modelzoo.data_preparation.data_preprocessing.hooks:prompt_completion_text_read_hook"
  read_hook_kwargs:
    prompt_key: "prompt"
    completion_key: "completion"
  shuffle: true
  shuffle_seed: 13

dataset:
  pack_sequences: true
