trainer:
  init:
    model_dir: ./model_dir
    seed: 1
    backend:
      backend_type: CSX
      cluster_config:
        max_wgt_servers: 24
        num_workers_per_csx: 1
    model:
      name: mixtral
      vocab_size: 32000
      hidden_size: 4096
      position_embedding_type: rotary
      rotary_dim: 128
      rope_theta: 1000000.0
      share_embedding_weights: false
      max_position_embeddings: 2048
      embedding_dropout_rate: 0.0
      num_hidden_layers: 32
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      norm_type: rmsnorm
      num_heads: 32
      attention_type: scaled_dot_product
      attention_module: multiquery_attention
      extra_attention_params:
        num_kv_groups: 8
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: false
      use_ffn_bias_in_attention: false
      filter_size: 14336
      nonlinearity: swiglu
      use_ffn_bias: false
      moe:
        num_experts: 8
        top_k: 2
        load_balancing_loss_coef: 0.02
        router_fp32: true
      use_bias_in_output: false
    optimizer:
      AdamW:
        betas:
        - 0.9
        - 0.95
        correct_bias: true
        weight_decay: 0.1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            end_learning_rate: 3.75e-05
            total_iters: 2000
        - CosineDecayLR:
            initial_learning_rate: 0.0003
            end_learning_rate: 3.0e-05
            total_iters: 236418
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 2000
      eval_steps: 200
      eval_frequency: 200
    checkpoint:
      steps: 200
      save_initial_checkpoint: true
    logging:
      log_steps: 100
    callbacks:
    - ScopedTrainFlags:
        csx.performance.micro_batch_size: 4
    - ScopedValidateFlags:
        csx.performance.micro_batch_size: 4
    - Lora:
        lora_params:
          r: 16
          alpha: 32
          dropout: 0.05
          target_modules:
          - Linear
          merge_weights: false
  fit:
    train_dataloader:
      data_processor: GptHDF5DataProcessor
      data_dir: /home/ebereuwadoka/project3-sparse-ft/data/cs_hdf5/mixtral/boolq/train
      batch_size: 256
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader:
    - &id001
      data_processor: GptHDF5DataProcessor
      data_dir: /home/ebereuwadoka/project3-sparse-ft/data/cs_hdf5/mixtral/boolq/val
      batch_size: 12
      shuffle: false
      num_workers: 8
  validate:
    val_dataloader: *id001
  validate_all:
    val_dataloaders:
    - *id001
