setup:
  data:
    type: "local"
    source: "/tmp/csdp_llama3-gsm8k-train.UbUL"   # directory containing *.jsonl (or a tmp dir with a symlink)
  mode: "finetuning"
  output_dir: "data/cs_hdf5/llama3/gsm8k/train"
  processes: 8

processing:
  huggingface_tokenizer: "meta-llama/Llama-3.1-8B-Instruct"
  max_seq_length: 2048
  read_hook: "cerebras.modelzoo.data_preparation.data_preprocessing.hooks:prompt_completion_text_read_hook"
  read_hook_kwargs:
    prompt_key: "prompt"
    completion_key: "completion"
  shuffle: true
  shuffle_seed: 13

dataset:
  pack_sequences: true
